name: Deploy catalog-server

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: release

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: "JZoaH78eeFL4KXGLHVBOX2TE"
          VERCEL_ORG_ID: "yH1Kc6EBTIFS1Sd9AM61TKXH"
          VERCEL_PROJECT_ID: "prj_OT42nrXEw77iXE9HjIf56xXKuEvW"
        run: vercel --token $VERCEL_TOKEN --prod
